server:
  port: 8084
spring:
  application:
    name: matching-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: matching-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.rideMatcher.matchingservice.event.RideRequestedEvent

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


location:
  service:
    url: http://localhost:8082
management:
  endpoints:
    web:
      exposure:
        include: health, info
